[add] mock api worker추가 (서버처럼작동)
chit-a-chat/FE pull request #7
Opened 2024-07-27 15:37 UTC by YoonDongGeun

### 추가 라이브러리
- msw (mock service worker) => 브라우저 서비스 워커로 동작

### mock api server 추가
- axios.get(경로)로 요청 보내면, 원하는 데이터 오도록 기능 추가

2024-07-31 13:43 UTC, hani2057 requested changes

2024-07-31 13:43 UTC, hani2057 commented on package.json
prettier 설정 tabWidth 2로 되어 있는 것 같습니다. 확인 부탁드립니다. (커밋 전에 프리티어 돌리는 설정 안 되어 있는 것 같아요 확인하고 추가하겠습니다.)

2024-07-31 13:43 UTC, hani2057 commented on src/app/index.tsx
> +    });
예시 코드 대신 실행할 함수(서비스콜)을 받아서 호출하는 함수로 변경하여 바로 사용할 수 있도록 하면 더 좋을 것 같아요! (해주세요😊)

2024-08-01 03:26 UTC, YoonDongGeun commented on package.json
헉 그렇네요.. .json 추가하는 방향을하겠습니다!! 
확인해주셔서 감사합니다.

2024-08-03 15:21 UTC, YoonDongGeun commented on src/app/index.tsx
> +    });
MockApiServer ON/OFF 하여 사용할 수 있도록 수정하였습니다.

2024-08-06 02:02 UTC, hani2057 approved these changes

2024-08-06 02:03 UTC, merged